name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Setup signing configure
      run: |
        echo "${{ secrets.RELEASE_KEYSTORE }}" | base64 -d > release.keystore ;
        echo "signingStoreLocation=../release.keystore" > keystore.properties ;
        echo "signingStorePassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> keystore.properties ;
        echo "signingKeyAlias=release" >> keystore.properties ;
        echo "signingKeyPassword=${{ secrets.RELEASE_KEYSTORE_PASSWORD }}" >> keystore.properties ;
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Upload APK To Artifact
      uses: actions/upload-artifact@v3
      with:
        name: apk
        path: |
          app/build/outputs/apk/release/*
